"""Add UUID column to encrypted asset.

Revision ID: f664f785be72
Revises: 
Create Date: 2025-03-17 10:02:32.505802

"""
from alembic import op
import sqlalchemy as sa
#import f664f785be72_add_uuid_column_to_encrypted_asset
from models import Vault, EncryptedAsset
import uuid

# revision identifiers, used by Alembic.
revision = 'f664f785be72'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_uuid', sa.String(length=256), nullable=True))

    for ea in EncryptedAsset.query.all():
        ea.asset_uuid = uuid.uuid4()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_asset', schema=None) as batch_op:
        batch_op.drop_column('asset_uuid')

    # ### end Alembic commands ###
