version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - FLASK_DEBUG=true
      - DATABASE_URL=sqlite:///data/vaultdb.sqlite3
    volumes:
      - ./data:/app/data  # Map SQLite to host
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - flask-app
