version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    restart: always
    environment:
      - FLASK_DEBUG=false
      - SQLITE_DB=sqlite:///vaultdb.sqlite3
      - JWT_SECRET_KEY=nevergonnagiveyouupnevergonnaletyoudown
    volumes:
      - ./data:/app/instance  # Map SQLite to host
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - flask-app
